name = "daily-life-tracker-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-12-28"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "daily-life-tracker-db"
database_id = "0660eee2-92ef-4105-a5f9-86cd500afe8e"
migrations_dir = "worker/db/migrations"
